// This protobuf defines a new cloudprober probe type.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v3.21.5
// source: github.com/jumpojoy/osprober/arping/arping.proto

package arping

import (
	proto "github.com/cloudprober/cloudprober/probes/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProbeConf struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxWorkers    *int32                 `protobuf:"varint,1,opt,name=max_workers,json=maxWorkers,def=250" json:"max_workers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for ProbeConf fields.
const (
	Default_ProbeConf_MaxWorkers = int32(250)
)

func (x *ProbeConf) Reset() {
	*x = ProbeConf{}
	mi := &file_github_com_jumpojoy_osprober_arping_arping_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeConf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeConf) ProtoMessage() {}

func (x *ProbeConf) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_jumpojoy_osprober_arping_arping_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeConf.ProtoReflect.Descriptor instead.
func (*ProbeConf) Descriptor() ([]byte, []int) {
	return file_github_com_jumpojoy_osprober_arping_arping_proto_rawDescGZIP(), []int{0}
}

func (x *ProbeConf) GetMaxWorkers() int32 {
	if x != nil && x.MaxWorkers != nil {
		return *x.MaxWorkers
	}
	return Default_ProbeConf_MaxWorkers
}

var file_github_com_jumpojoy_osprober_arping_arping_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*proto.ProbeDef)(nil),
		ExtensionType: (*ProbeConf)(nil),
		Field:         200,
		Name:          "osprober.arping_probe",
		Tag:           "bytes,200,opt,name=arping_probe",
		Filename:      "github.com/jumpojoy/osprober/arping/arping.proto",
	},
}

// Extension fields to proto.ProbeDef.
var (
	// optional osprober.ProbeConf arping_probe = 200;
	E_ArpingProbe = &file_github_com_jumpojoy_osprober_arping_arping_proto_extTypes[0]
)

var File_github_com_jumpojoy_osprober_arping_arping_proto protoreflect.FileDescriptor

var file_github_com_jumpojoy_osprober_arping_arping_proto_rawDesc = []byte{
	0x0a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x75, 0x6d,
	0x70, 0x6f, 0x6a, 0x6f, 0x79, 0x2f, 0x6f, 0x73, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x2f, 0x61,
	0x72, 0x70, 0x69, 0x6e, 0x67, 0x2f, 0x61, 0x72, 0x70, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x08, 0x6f, 0x73, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x1a, 0x3c, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x70, 0x72,
	0x6f, 0x62, 0x65, 0x72, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x72,
	0x2f, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x31, 0x0a, 0x09, 0x50, 0x72,
	0x6f, 0x62, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x12, 0x24, 0x0a, 0x0b, 0x6d, 0x61, 0x78, 0x5f, 0x77,
	0x6f, 0x72, 0x6b, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x3a, 0x03, 0x32, 0x35,
	0x30, 0x52, 0x0a, 0x6d, 0x61, 0x78, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x73, 0x3a, 0x55, 0x0a,
	0x0c, 0x61, 0x72, 0x70, 0x69, 0x6e, 0x67, 0x5f, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x12, 0x1c, 0x2e,
	0x63, 0x6c, 0x6f, 0x75, 0x64, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x62,
	0x65, 0x73, 0x2e, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x44, 0x65, 0x66, 0x18, 0xc8, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6f, 0x73, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x72, 0x2e, 0x50, 0x72,
	0x6f, 0x62, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x52, 0x0b, 0x61, 0x72, 0x70, 0x69, 0x6e, 0x67, 0x50,
	0x72, 0x6f, 0x62, 0x65, 0x42, 0x25, 0x5a, 0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6a, 0x75, 0x6d, 0x70, 0x6f, 0x6a, 0x6f, 0x79, 0x2f, 0x6f, 0x73, 0x70, 0x72,
	0x6f, 0x62, 0x65, 0x72, 0x2f, 0x61, 0x72, 0x70, 0x69, 0x6e, 0x67,
}

var (
	file_github_com_jumpojoy_osprober_arping_arping_proto_rawDescOnce sync.Once
	file_github_com_jumpojoy_osprober_arping_arping_proto_rawDescData = file_github_com_jumpojoy_osprober_arping_arping_proto_rawDesc
)

func file_github_com_jumpojoy_osprober_arping_arping_proto_rawDescGZIP() []byte {
	file_github_com_jumpojoy_osprober_arping_arping_proto_rawDescOnce.Do(func() {
		file_github_com_jumpojoy_osprober_arping_arping_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_jumpojoy_osprober_arping_arping_proto_rawDescData)
	})
	return file_github_com_jumpojoy_osprober_arping_arping_proto_rawDescData
}

var file_github_com_jumpojoy_osprober_arping_arping_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_github_com_jumpojoy_osprober_arping_arping_proto_goTypes = []any{
	(*ProbeConf)(nil),      // 0: osprober.ProbeConf
	(*proto.ProbeDef)(nil), // 1: cloudprober.probes.ProbeDef
}
var file_github_com_jumpojoy_osprober_arping_arping_proto_depIdxs = []int32{
	1, // 0: osprober.arping_probe:extendee -> cloudprober.probes.ProbeDef
	0, // 1: osprober.arping_probe:type_name -> osprober.ProbeConf
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_github_com_jumpojoy_osprober_arping_arping_proto_init() }
func file_github_com_jumpojoy_osprober_arping_arping_proto_init() {
	if File_github_com_jumpojoy_osprober_arping_arping_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_jumpojoy_osprober_arping_arping_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_github_com_jumpojoy_osprober_arping_arping_proto_goTypes,
		DependencyIndexes: file_github_com_jumpojoy_osprober_arping_arping_proto_depIdxs,
		MessageInfos:      file_github_com_jumpojoy_osprober_arping_arping_proto_msgTypes,
		ExtensionInfos:    file_github_com_jumpojoy_osprober_arping_arping_proto_extTypes,
	}.Build()
	File_github_com_jumpojoy_osprober_arping_arping_proto = out.File
	file_github_com_jumpojoy_osprober_arping_arping_proto_rawDesc = nil
	file_github_com_jumpojoy_osprober_arping_arping_proto_goTypes = nil
	file_github_com_jumpojoy_osprober_arping_arping_proto_depIdxs = nil
}
